name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Compilation & Style
      id: compilation-style
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Compilation & Style
        setup-command: ''
        command: javac *.java
        timeout: 2
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        COMPILATION-STYLE_RESULTS: "${{steps.compilation-style.outputs.result}}"
      with:
        runners: compilation-style
